version: 1
update_configs:
  - package_manager: "javascript"
    directory: "web/app/"
    update_schedule: "daily"
    default_reviewers:
    - "MrBenJ"
  - package_manager: "javascript"
    directory: "web/init/"
    update_schedule: "daily"
    default_reviewers:
    - "MrBenJ"

  - package_manager: "go:dep"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
    - "laverya"

  - package_manager: "docker"
    directory: "deploy/"
    update_schedule: "daily"
    default_reviewers:
    - "laverya"
